### ISSUE TITLE
Frontend helpers for making issuing commands easier to work with

### ISSUE THREAD

**Issue by pavsaund** [dolittle-interaction/JavaScript.Client#10]
Issuing a command is currently possible by using the CommandCoordinator, and passing in the appropriate generated proxy.

What would be very useful to have helper features that capture the behaviour of the lifecycle of issuing commands. The idea would be to have a framework-agnostic object(s) that had the intended behaviour exposed that could be used directly in applications, or wrapped in framework specific components (bindinghandlers, actual components etc). Here's an initial list that can be split up into different tasks and milestones.

Before Issuing:
 - Frontend Input validation generated based on metadata from the domain. For properties and for the command in general.
 - Dirty-tracking of properties on a command, with the possibility to set initial values.
 - CanExecute based on validation & authorization (and more?).
 
While issuing:
 - IsBusy flag that tells if a command is being issues

After issuing:
 - Populating validation errors from server to the command object so that it can be bound to the view
 - Same as above for exceptions from the server.
 - Reseting a command, or clearing the isDirty flag
 - Getting the updated readmodels based on events in the system (perhaps push-based?)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1115619539252805)

**Comment by einari** [comment]
Suggestion:

For the command and avoiding Command Coordinator. What if we created a bridge for every framework to enable something like:

<button dolittle:Command="{MyCommandInstance}"/>

I believe this should be possible with Aurelia and Angular at least.

**Comment by einari** [comment]
Suggestion: 
To keep concerns separate and not mix in `CommandCoordinator` in a command - we can compose this with extensions - enabling for instance:

```xml
<button dolittle:Command="{MyCommandInstance}"/>
```

The extension would then have a dependency to the `CommandCoordinator` and issue it on click and enable and disable the button if the command can't be executed. 

This should be possible to do with both Aurelia and Angular, possibly also with React. It would be a bridge specific to these.

/cc: @smithmx
