### ISSUE TITLE
Throw exeption from promise using .catch

### ISSUE THREAD

**Issue by Parjoona** [dolittle-interaction/JavaScript.Client#14]
### Expected behavior
When using try / catch or .then().catch() when interacting with the dolittle commandCoordinator/queryCoordinator I would like to throw an error depeding on the input validations from the backend.

### Actual behavior
Dolittle does not throw any errors from the promise it gets from the backend.
When errorhanding you need to check the json response for the error field.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1115619641957549)

**Comment by pavsaund** [comment]
Hi @Parjoona, thanks for the issue and sorry for the delayed response.

The intent is to make a clear distinction between an error that occurs within the command/query pipeline and an unexpected error that occurs outside the pipeline (e.g. network issues, server timeouts etc).

If the response has been handled by the server you need to handle the response explicitly by checking the `success`-flag on the command or query result, and digging into the `exception`-property. 

To handle any errors that happen outside the pipeline itself, you'll need to inspect the error that bubbles up from the promise in the Coordinator using a `.catch()`;

We don't have a Javascript representation available, but the structure is as defined in the Runtime: [QueryResult.cs](https://github.com/dolittle-runtime/Runtime/blob/d7aa7f7127eabdbf424424a92f1e13828899c5fe/Source/Queries/QueryResult.cs) & [CommandResult.cs](https://github.com/dolittle-runtime/Runtime/blob/d7aa7f7127eabdbf424424a92f1e13828899c5fe/Source/Commands/CommandResult.cs).

**Comment by pavsaund** [comment]
@Parjoona: ValidationErrors from Input or Business Validators are exposed on the `result.validationResults` property on the command result and the `success`property will be false.
