### ISSUE TITLE
How to override request headers for queries and commands?

### ISSUE THREAD

**Issue by pavsaund** [dolittle-interaction/JavaScript.Client#16]
I need to send custom authorization headers on each request, as well as deal with the response to correctly deal with redirects. This means overriding with custom headers when sending commands or querying.

The implementations for [CommandCoordinator](https://github.com/dolittle-interaction/JavaScript.Client/blob/b73915ad2a0bd2ccc0754f629e64c19d5f053587/Source/commands/CommandCoordinator.js#L19) and [QueryCoordinator](https://github.com/dolittle-interaction/JavaScript.Client/blob/b73915ad2a0bd2ccc0754f629e64c19d5f053587/Source/queries/QueryCoordinator.js#L19) both use the native `fetch`-api for requests.

I'm currently solving this by overriding the default fetch implementation in my application's startup like so:

```javascript
const originalFetch = fetch;
fetch = function customFetch(input, init) {
    /// header logic
    return originalFetch(input, init)
                     .then(response => { // custom response logic });
}

```

This seems like a dirty hack, and something that could potentially be handled in the API's for the Coordinators themselves? Do you have any thoughts on a better short / long-term solution @einari?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1129334945804947)

**Comment by pavsaund** [comment]
So, I suppose the custom response logic can be handled in the app in another place. The main focus are the request header overrides.

**Comment by einari** [comment]
This is now fixed by using the two new static methods on `QueryCoordinator` and `CommandCoordinator` called `beforeExecute` and `beforeHandle`. What these does is add a callback that gets called before everytime a query executes or a command gets handled with the parameter of the fetch options object.

**Comment by pavsaund** [comment]
test

**Comment by pavsaund** [comment]
another test
